// <auto-generated />
using System;
using Internship_7_Moodle.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Internship_7_Moodle.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231144050_MigrationUpdateSeed")]
    partial class MigrationUpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Chats.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserAId")
                        .HasColumnType("integer")
                        .HasColumnName("user_a_id");

                    b.Property<int>("UserBId")
                        .HasColumnType("integer")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id");

                    b.HasIndex("UserBId");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique();

                    b.ToTable("chats", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            UserAId = 1,
                            UserBId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UserAId = 1,
                            UserBId = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            UserAId = 1,
                            UserBId = 2
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("Ects")
                        .HasColumnType("integer")
                        .HasColumnName("ects");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("courses", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Osnove algebre i teorije brojeva.",
                            Ects = 7,
                            Name = "Matematika 1",
                            OwnerId = 6,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Integrali i diferencijalne jednadžbe.",
                            Ects = 7,
                            Name = "Matematika 2",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Osnovni koncepti OOP-a",
                            Ects = 6,
                            Name = "Objektno orijentirano programiranje",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Proučavanje vremena izvršavanja i optimizacije algoritama za sortiranje i pretraživanje.",
                            Ects = 6,
                            Name = "Algoritmi",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Osnove interneta.",
                            Ects = 5,
                            Name = "Računalne mreže",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uvod u digitalnu logiku.",
                            Ects = 6,
                            Name = "Diskretni sustavi i strukture",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stvaranje vlastite računalne mreže kroz parktični rad.",
                            Ects = 6,
                            Name = "Praktična izrada računalnih mreža",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Upoznavanje s programskim jezikom C i zapisom brojeva na računalima.",
                            Ects = 4,
                            Name = "Uvod u računala i programiranje",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pokazivači i structovi te njihova primjena u C jeziku",
                            Ects = 7,
                            Name = "Programiranje",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Upoznavanje s osnovnim strukturama podataka i vremenom izvršavanja",
                            Ects = 8,
                            Name = "Strukture podataka",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Linijski integrali i vektorska polja.",
                            Ects = 6,
                            Name = "Matematika 3",
                            OwnerId = 6,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teorija brojeva i kombinatorika.",
                            Ects = 5,
                            Name = "Diskretna matematika",
                            OwnerId = 6,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teorija ekonomije i poduzetništva.",
                            Ects = 3,
                            Name = "Ekonomija",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matematika iza prikaza računalne grafike.",
                            Ects = 5,
                            Name = "Računalna grafika",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teorija obrade signala.",
                            Ects = 4,
                            Name = "Signali i sustavi",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.CourseMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author_name");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_materials", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ivo Ivić",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2015, 1, 1),
                            Title = "Matematika1 FESB",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/ivo/Matematika1%20FESB.pdf"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Ivo Ivić",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2015, 1, 1),
                            Title = "Zbirka zadataka 2015",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/ivo/Zbirka%zadataka%2015/"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Petar Petrović",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2017, 3, 28),
                            Title = "Uvod u viševarijabilni račun",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/petar/multivariable%calculus/"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Petar Petrović",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2018, 4, 27),
                            Title = "Uvod u integralni račun",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/petar/integrals%book/"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Marjan Marjanović",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2003, 11, 11),
                            Title = "OOP skripta, FESB 2003",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/marjanovic/oop%skripta/"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Bjourn Stroustrup",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(1986, 2, 27),
                            Title = "The C++ programming Language",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.stroustrup.com/4th.html"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Hrvoje Hrvojić",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2010, 2, 27),
                            Title = "„Algoritmi“, interna skripta",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/hrvojic/interna%skripta/"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "T.Cormen",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(202, 5, 14),
                            Title = "„Introduction to Algorithms“, second edition",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.cs.mcgill.ca/~akroit/math/compsci/Cormen%20Introduction%20to%20Algorithms.pdf"
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.CourseNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_notifications", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Poštovani,\nzbog bolesti otkazujem sutrašnje predavanje.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 10, 26, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Otkazano predavanje",
                            UpdatedAt = new DateTime(2025, 10, 26, 11, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Poštovani,\nsutra se održava prvi kolokvij iz kolegija Matematika 1.\nMolimo ponesite iksice i pribor za pisanje.Ostalo je zabranjeno.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Prvi kolokvij",
                            UpdatedAt = new DateTime(2025, 11, 26, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Poštovani,\nNapomena: tko nije položio prvi kolokvij ne može izaći na drugi.Morati će čekati do ispitnog roka.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 11, 30, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Drugi kolokvij",
                            UpdatedAt = new DateTime(2025, 11, 30, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Poštovani,\nna predavanju idući tjedan održati će se teorijski ispit za dodatne bodove.\nGradivo koje ulazi u ispit: Dvostruki integrali.",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 11, 18, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Teorijski ispit za bodove",
                            UpdatedAt = new DateTime(2025, 11, 18, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Poštovani,\nu prilogu se nalaze rezultati kolokvija.\nhttps://moodle.rezultati/prvi_kolokvij.pdf",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Rezultati prvog kolokvija",
                            UpdatedAt = new DateTime(2025, 11, 29, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Poštovani,\nrok za predaju praktičnog rada kojeg smo spominjali na predavanju je 10.1.2026.\nOcjena iz praktičnog rada nosi 40% završne ocjene.",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Praktični rad",
                            UpdatedAt = new DateTime(2025, 12, 1, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Poštovani,\nsutrašnje predavanje održati će se u sali A102 (umjesto u predviđenoj A302)",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Promjena dvorane",
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Poštovani,\nidući tjedan (8.10.) počinju laboratorijske vježbe iz kolegija algoritmi.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 10, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Laboratorijske vježbe",
                            UpdatedAt = new DateTime(2025, 10, 1, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Poštovani,\nidući tjedan (25.10.) predavanje će se održati s početkom u 11:45 (umjesto 10:45) u sali A101.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 10, 18, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Promjena rasporeda",
                            UpdatedAt = new DateTime(2025, 10, 18, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Messages.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("private_messages", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 8,
                            SenderId = 1,
                            Text = "Poštovani,\nimam nedoumica u vezi predavanja o polimorfizmu i nasljeđivanju.Možete li dodatno pojasniti polimorfizam.",
                            UpdatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 1,
                            SenderId = 8,
                            Text = "Poštovani,\nHvala na pitanju! 🙂\nPolimorfizam je koncept u objektno-orijentiranom programiranju koji omogućava da se ista metoda ili operacija ponaša različito ovisno o tipu objekta koji je poziva.\nU praksi, to znači da možete imati baznu klasu s apstraktnom ili virtualnom metodom, a različite izvedene klase mogu implementirati tu metodu na svoj način.\nKada pozovete metodu preko referenci na baznu klasu, program automatski izvršava implementaciju odgovarajuće izvedene klase.\nAko želite, možemo na primjeru vaše konzolne aplikacije s MenuManager klasama pokazati kako polimorfizam radi u stvarnom kodu.\nNadam se da ovo pojašnjava. Javite ako želite detaljniji primjer koda.",
                            UpdatedAt = new DateTime(2025, 11, 11, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 10,
                            SenderId = 1,
                            Text = "Poštovani,\nimam pitanje u vezi ažuriranja profila.Na kraju godine ću postati profesor te sam htio pitati je li moguća promjena uloge.",
                            UpdatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ChatId = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 1,
                            SenderId = 10,
                            Text = "Poštovani,\nvaša uloga će biti promijenjena kada postanete profesor,pratiti ćemo novosti.",
                            UpdatedAt = new DateTime(2025, 10, 3, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ChatId = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 2,
                            SenderId = 1,
                            Text = "Bok,jel imaš skriptu iz Matematike 1 slučajno?",
                            UpdatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ChatId = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 14, 7, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 1,
                            SenderId = 2,
                            Text = "Bok,imam naravno,sutra ti dam na faksu.",
                            UpdatedAt = new DateTime(2025, 12, 3, 14, 7, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.PivotTables.CourseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("course_users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("roles", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Može samo gledati podatke o kolegijima (nema prava da išta izmijeni)",
                            RoleName = "Student",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Može dodavati studente u kolegije te slati obavijesti i materijale",
                            RoleName = "Professor",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ima ovlasti brisati i dodavati korisnike bilo koje uloge",
                            RoleName = "Admin",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2000, 4, 4),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zandzartz@gmail.com",
                            FirstName = "John",
                            Gender = "M",
                            LastName = "Doe",
                            Password = "AQAAAAEAACcQAAAAEG7bZmjIDmJEy/YFuaaKIZE/UG3AhwodxbqiHbRkKlmpfFrh5IKdwBDAeDLbHg0m5g==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2000, 3, 3),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dorianleci@gmail.com",
                            FirstName = "Dorian",
                            Gender = "M",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEETg2SiRxbT7W9TG7YxTyoeXND+ypT6pOaTjXBSNOryrIG0qDnpd+v/sd8qIb9ck3A==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2004, 3, 28),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "damirleci@gmail.com",
                            FirstName = "Damir",
                            Gender = "M",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEEZAXTSPjNWTNHqPHlrgg6oxYz4So00rVGU2P0qM1UcXNyyv8NhKu+SRWnXVegKc6A==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2005, 11, 28),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vesnaleci@gmail.com",
                            FirstName = "Vesna",
                            Gender = "F",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAED15gaHrOCCbsmf5o+31bLkZvf7Z6RGFhU1H+yvUsNEUT8NZtHB3+OF1m6rFCVlVMQ==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1990, 10, 12),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zoraleci@gmail.com",
                            FirstName = "Zora",
                            Gender = "F",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEDHFyUR6hjKRm6tZmojd8mbRbqw4zc+H4dZBoUCMn/4kgjut1pZ9ydAdYuBJj7UCjQ==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1989, 9, 12),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivoivić@gmail.com",
                            FirstName = "Ivo",
                            Gender = "M",
                            LastName = "Ivić",
                            Password = "AQAAAAEAACcQAAAAEBIcHEUG2o2nVHVQePi9oC5NSfSpBmWXh0g4kRCHT7+F2zMhUq4/f/HAagUj9Akxjw==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1988, 9, 12),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petarpetrović@gmail.com",
                            FirstName = "Petar",
                            Gender = "M",
                            LastName = "Petrović",
                            Password = "AQAAAAEAACcQAAAAEMx2u7Y/OwAkDxtHQQ0PU6ZJG9Nc9uOghA+6/swAwxJMDXS8ZIkRv/DXg/wCLikvYA==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1995, 1, 1),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "majamajić@gmail.com",
                            FirstName = "Maja",
                            Gender = "F",
                            LastName = "Majić",
                            Password = "AQAAAAEAACcQAAAAEItSw6u6wgLd3zV3/q/BJ2oN93o0QWx/OyXAs6C0tUNL5sjR8zOGkGyhwuuU64b66A==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1997, 2, 2),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vesnavesnić@gmail.com",
                            FirstName = "Vesna",
                            Gender = "F",
                            LastName = "Vesnić",
                            Password = "AQAAAAEAACcQAAAAEA+i9AG8TR0lT6tXw/mAIPkMp7Vc0bIXW3tmz6EuYxiqkQdTessI2AXEzgie5n610Q==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1997, 3, 8),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sebaleci@gmail.com",
                            FirstName = "Sebastian",
                            Gender = "M",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEBtIu4uqeRMJFV/9qTJz/Hquywc1PnTtnlEbPe63owuwCsNYoHzl3nc04RB68UEmxw==",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1997, 3, 8),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikolaf@gmail.com",
                            FirstName = "Nikola",
                            Gender = "M",
                            LastName = "Filipović",
                            Password = "AQAAAAEAACcQAAAAECGtn2o0rNWvFWCqIox9S3DkRCnbXn2MXpJEovxW8p01TY+YrvuKLpntTbROouZDfA==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Chats.Chat", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "UserA")
                        .WithMany("ChatsAsUserA")
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "UserB")
                        .WithMany("ChatsAsUserB")
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.CourseMaterial", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.CourseNotification", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Notifications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Messages.PrivateMessage", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Chats.Chat", "Chat")
                        .WithMany("PrivateMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.PivotTables.CourseUser", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "User")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Chats.Chat", b =>
                {
                    b.Navigation("PrivateMessages");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("Materials");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("ChatsAsUserA");

                    b.Navigation("ChatsAsUserB");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
