// <auto-generated />
using System;
using Internship_7_Moodle.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Internship_7_Moodle.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101211535_MigrationUpdateRequired")]
    partial class MigrationUpdateRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Chats.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserAId")
                        .HasColumnType("integer")
                        .HasColumnName("user_a_id");

                    b.Property<int>("UserBId")
                        .HasColumnType("integer")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id");

                    b.HasIndex("UserBId");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique();

                    b.ToTable("chats", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            UserAId = 1,
                            UserBId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UserAId = 1,
                            UserBId = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            UserAId = 1,
                            UserBId = 2
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("Ects")
                        .HasColumnType("integer")
                        .HasColumnName("ects");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("courses", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Osnove algebre i teorije brojeva.",
                            Ects = 7,
                            Name = "Matematika 1",
                            OwnerId = 6,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Integrali i diferencijalne jednadžbe.",
                            Ects = 7,
                            Name = "Matematika 2",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Osnovni koncepti OOP-a",
                            Ects = 6,
                            Name = "Objektno orijentirano programiranje",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Proučavanje vremena izvršavanja i optimizacije algoritama za sortiranje i pretraživanje.",
                            Ects = 6,
                            Name = "Algoritmi",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Osnove interneta.",
                            Ects = 5,
                            Name = "Računalne mreže",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uvod u digitalnu logiku.",
                            Ects = 6,
                            Name = "Diskretni sustavi i strukture",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stvaranje vlastite računalne mreže kroz parktični rad.",
                            Ects = 6,
                            Name = "Praktična izrada računalnih mreža",
                            OwnerId = 9,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Upoznavanje s programskim jezikom C i zapisom brojeva na računalima.",
                            Ects = 4,
                            Name = "Uvod u računala i programiranje",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pokazivači i structovi te njihova primjena u C jeziku",
                            Ects = 7,
                            Name = "Programiranje",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Upoznavanje s osnovnim strukturama podataka i vremenom izvršavanja",
                            Ects = 8,
                            Name = "Strukture podataka",
                            OwnerId = 8,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Linijski integrali i vektorska polja.",
                            Ects = 6,
                            Name = "Matematika 3",
                            OwnerId = 6,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teorija brojeva i kombinatorika.",
                            Ects = 5,
                            Name = "Diskretna matematika",
                            OwnerId = 6,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teorija ekonomije i poduzetništva.",
                            Ects = 3,
                            Name = "Ekonomija",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matematika iza prikaza računalne grafike.",
                            Ects = 5,
                            Name = "Računalna grafika",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teorija obrade signala.",
                            Ects = 4,
                            Name = "Signali i sustavi",
                            OwnerId = 7,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Materials.CourseMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author_name");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_materials", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ivo Ivić",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2015, 1, 1),
                            Title = "Matematika1 FESB",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/ivo/Matematika1%20FESB.pdf"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Ivo Ivić",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2015, 1, 1),
                            Title = "Zbirka zadataka 2015",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/ivo/Zbirka%zadataka%2015/"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Petar Petrović",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2017, 3, 28),
                            Title = "Uvod u viševarijabilni račun",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/petar/multivariable%calculus/"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Petar Petrović",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2018, 4, 27),
                            Title = "Uvod u integralni račun",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/petar/integrals%book/"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Marjan Marjanović",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2003, 11, 11),
                            Title = "OOP skripta, FESB 2003",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/marjanovic/oop%skripta/"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Bjourn Stroustrup",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(1986, 2, 27),
                            Title = "The C++ programming Language",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.stroustrup.com/4th.html"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Hrvoje Hrvojić",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2010, 2, 27),
                            Title = "„Algoritmi“, interna skripta",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/hrvojic/interna%skripta/"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "T.Cormen",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2020, 5, 14),
                            Title = "„Introduction to Algorithms“, second edition",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.cs.mcgill.ca/~akroit/math/compsci/Cormen%20Introduction%20to%20Algorithms.pdf"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Ante Antić",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2020, 5, 15),
                            Title = "Fizička razina",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/antic/fizicka%razina/"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "Ante Antić",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2020, 5, 15),
                            Title = "Podatkovna razina",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/antic/podatkovna%razina/"
                        },
                        new
                        {
                            Id = 11,
                            AuthorName = "Ante Antić",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2020, 5, 15),
                            Title = "Transportna razina",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/antic/transportna%razina/"
                        },
                        new
                        {
                            Id = 12,
                            AuthorName = "David Davidović",
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2010, 5, 15),
                            Title = "Booleova algebra",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/davidovic/booleova%algebra/"
                        },
                        new
                        {
                            Id = 13,
                            AuthorName = "David Davidović",
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2008, 5, 15),
                            Title = "Digitalni sklopovi (1.izadnje)",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/davidovic/digitalni%sklopovi1/"
                        },
                        new
                        {
                            Id = 14,
                            AuthorName = "Vesna Vesnić",
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2007, 3, 14),
                            Title = "Računalne mreže u sklopovlju(2007)",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/vesnic/mreze%sklopovlje/"
                        },
                        new
                        {
                            Id = 15,
                            AuthorName = "Robert Cecil Martin",
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2005, 4, 18),
                            Title = "Clean Code",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://ptgmedia.pearsoncmg.com/images/9780132928472/samplepages/0132928477.pdf"
                        },
                        new
                        {
                            Id = 16,
                            AuthorName = "Dennis Ritchie",
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(1988, 1, 12),
                            Title = "The C Programming Language. 2nd Edition",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://seriouscomputerist.atariverse.com/media/pdf/book/C%20Programming%20Language%20-%202nd%20Edition"
                        },
                        new
                        {
                            Id = 17,
                            AuthorName = "Maja Majić",
                            CourseId = 9,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2013, 1, 13),
                            Title = "Zbirka zadataka-C",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/majic/zbirka%zadatakac/"
                        },
                        new
                        {
                            Id = 18,
                            AuthorName = "Petar Petrović",
                            CourseId = 13,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateOnly(2013, 7, 13),
                            Title = "Uvod u ekonomiju i poduzetništvo",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fesbmaterijali.net/petrovic/ekonimija%uvod/"
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Notifications.CourseNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_notifications", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Poštovani,\nzbog bolesti otkazujem sutrašnje predavanje.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 10, 26, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Otkazano predavanje",
                            UpdatedAt = new DateTime(2025, 10, 26, 11, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Poštovani,\nsutra se održava prvi kolokvij iz kolegija Matematika 1.\nMolimo ponesite iksice i pribor za pisanje.Ostalo je zabranjeno.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Prvi kolokvij",
                            UpdatedAt = new DateTime(2025, 11, 26, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Poštovani,\nNapomena: tko nije položio prvi kolokvij ne može izaći na drugi.Morati će čekati do ispitnog roka.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 11, 30, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Drugi kolokvij",
                            UpdatedAt = new DateTime(2025, 11, 30, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Poštovani,\nna predavanju idući tjedan održati će se teorijski ispit za dodatne bodove.\nGradivo koje ulazi u ispit: Dvostruki integrali.",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 11, 18, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Teorijski ispit za bodove",
                            UpdatedAt = new DateTime(2025, 11, 18, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Poštovani,\nu prilogu se nalaze rezultati kolokvija.\nhttps://moodle.rezultati/prvi_kolokvij.pdf",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Rezultati prvog kolokvija",
                            UpdatedAt = new DateTime(2025, 11, 29, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Poštovani,\nrok za predaju praktičnog rada kojeg smo spominjali na predavanju je 10.1.2026.\nOcjena iz praktičnog rada nosi 40% završne ocjene.",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Praktični rad",
                            UpdatedAt = new DateTime(2025, 12, 1, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Poštovani,\nsutrašnje predavanje održati će se u sali A102 (umjesto u predviđenoj A302)",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Promjena dvorane",
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Poštovani,\nidući tjedan (8.10.) počinju laboratorijske vježbe iz kolegija algoritmi.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 10, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Laboratorijske vježbe",
                            UpdatedAt = new DateTime(2025, 10, 1, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Poštovani,\nidući tjedan (25.10.) predavanje će se održati s početkom u 11:45 (umjesto 10:45) u sali A101.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 10, 18, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Promjena rasporeda",
                            UpdatedAt = new DateTime(2025, 10, 18, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Content = "Poštovani,\nidući tjedan (25.10.) predavanje će se održati s početkom u 11:45 (umjesto 10:45) u sali A102.",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 10, 18, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Promjena rasporeda",
                            UpdatedAt = new DateTime(2025, 10, 18, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Content = "Poštovani,\nu prvom mjesecu kreću laboratorijske vježbe.U prvom mjesecu će biti obavijest o rasporedu po grupama",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 3, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Laboratorijske vježbe",
                            UpdatedAt = new DateTime(2025, 12, 20, 15, 3, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Content = "Poštovani,\nNapomena u vezi laboratorijskih vježbi.Prije svake vježbe pisati će se ulazni ispiti.",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 12, 20, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Laboratorijske vježbe: Napomena",
                            UpdatedAt = new DateTime(2025, 12, 20, 16, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Content = "Poštovani,\nNapomena u vezi laboratorijskih vježbi.Prije svake vježbe pisati će se ulazni ispiti.",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 12, 20, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Laboratorijske vježbe: Napomena",
                            UpdatedAt = new DateTime(2025, 12, 20, 16, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Content = "Poštovani,\nu prvom mjesecu ću biti na poslovnom putu u Japanu,pa će asistent držati sva predavanja kroz mjesec.",
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 12, 21, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Promjena predavača",
                            UpdatedAt = new DateTime(2025, 12, 21, 16, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Content = "Poštovani,\ndobio sam dosta upita što se tiče konzultacija. Možete doći bilo kada dok sam na faksu,samo se najavite preko maila.",
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 11, 21, 13, 12, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Konzultacije",
                            UpdatedAt = new DateTime(2025, 11, 21, 13, 12, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Content = "Poštovani,\nrok za predaju praktičnog rada je do kraja prvog mjeseca.Sretno!",
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 12, 30, 13, 12, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Predaja praktičnog rada",
                            UpdatedAt = new DateTime(2025, 12, 30, 13, 12, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Content = "Poštovani,\novaj kolegij ne sadrži drugi kolokvij.U završnu ocjenu ulazi prvi kolokvij i ocjena iz praktičnog rada.",
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 12, 30, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Drugi kolokvij",
                            UpdatedAt = new DateTime(2025, 12, 30, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Content = "Poštovani,\ns obzirom da svake godine bude studenata koji su prije ovog kolegija naučili programirate,možete se prijaviti na predkolokvij.\nOdržati će se idući tjedan u uskoro najavljenom terminu.",
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 10, 10, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Pretkolokvij",
                            UpdatedAt = new DateTime(2025, 10, 10, 12, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Content = "Poštovani,\nobavijest za sve prijavljene na pretkolokvij.Održati će se 18.10 u 18:30 (laboratorij B420).",
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 10, 11, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Pretkolokvij-Termin",
                            UpdatedAt = new DateTime(2025, 10, 11, 12, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Content = "Poštovani,\nocjene na ovom kolegiju dodjeljuju se relativno.Najboljih 20% posto dobiti će ocjenu 5.\nSvakih 20% je nova ocjena niže.",
                            CourseId = 9,
                            CreatedAt = new DateTime(2025, 10, 11, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Način ocjenjivanja",
                            UpdatedAt = new DateTime(2025, 10, 11, 12, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Content = "Poštovani,\nprvi kolokvij piše se u laboratoriju B420.\nKolokvij se sadrži od 2 zadataka pod a) i b).Svaki točno riješeni nosi 10 bodova.",
                            CourseId = 9,
                            CreatedAt = new DateTime(2025, 11, 15, 7, 7, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Prvi kolokvij",
                            UpdatedAt = new DateTime(2025, 11, 15, 7, 7, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Content = "Poštovani,\nprije prvih laboratorijskih vježbi proučite upute za korištenje GitHub-a koje su spomenute na predavanju",
                            CourseId = 10,
                            CreatedAt = new DateTime(2025, 10, 15, 7, 7, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Strukture podataka-Laboratorijske vježbe",
                            UpdatedAt = new DateTime(2025, 10, 15, 7, 7, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Content = "Poštovani,\nzbog praznika koji počinju idući tjedan primorani smo odgoditi predavanje.Uskoro više o terminu...",
                            CourseId = 11,
                            CreatedAt = new DateTime(2025, 12, 18, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Praznici",
                            UpdatedAt = new DateTime(2025, 12, 18, 10, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Content = "Poštovani,\npredavanje odgođeno zbog praznika NEĆE se nadoknaditi jer smatram da smo prošli dovoljnu količinu gradiva do sada.",
                            CourseId = 11,
                            CreatedAt = new DateTime(2025, 12, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Praznici-Novi termin",
                            UpdatedAt = new DateTime(2025, 12, 20, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Content = "Poštovani,\ngradivo koje ulazi za prvi kolokvij je prvih 7 predavanja.\nSretne pripreme!",
                            CourseId = 13,
                            CreatedAt = new DateTime(2025, 11, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Subject = "Gradivo za prvi kolokvij",
                            UpdatedAt = new DateTime(2025, 11, 15, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Messages.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("private_messages", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 8,
                            SenderId = 1,
                            Text = "Poštovani,\nimam nedoumica u vezi predavanja o polimorfizmu i nasljeđivanju.Možete li dodatno pojasniti polimorfizam.",
                            UpdatedAt = new DateTime(2025, 11, 11, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 1,
                            SenderId = 8,
                            Text = "Poštovani,\nHvala na pitanju! 🙂\nPolimorfizam je koncept u objektno-orijentiranom programiranju koji omogućava da se ista metoda ili operacija ponaša različito ovisno o tipu objekta koji je poziva.\nU praksi, to znači da možete imati baznu klasu s apstraktnom ili virtualnom metodom, a različite izvedene klase mogu implementirati tu metodu na svoj način.\nKada pozovete metodu preko referenci na baznu klasu, program automatski izvršava implementaciju odgovarajuće izvedene klase.\nAko želite, možemo na primjeru vaše konzolne aplikacije s MenuManager klasama pokazati kako polimorfizam radi u stvarnom kodu.\nNadam se da ovo pojašnjava. Javite ako želite detaljniji primjer koda.",
                            UpdatedAt = new DateTime(2025, 11, 11, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 10,
                            SenderId = 1,
                            Text = "Poštovani,\nimam pitanje u vezi ažuriranja profila.Na kraju godine ću postati profesor te sam htio pitati je li moguća promjena uloge.",
                            UpdatedAt = new DateTime(2025, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ChatId = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 1,
                            SenderId = 10,
                            Text = "Poštovani,\nvaša uloga će biti promijenjena kada postanete profesor,pratiti ćemo novosti.",
                            UpdatedAt = new DateTime(2025, 10, 3, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ChatId = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 2,
                            SenderId = 1,
                            Text = "Bok,jel imaš skriptu iz Matematike 1 slučajno?",
                            UpdatedAt = new DateTime(2025, 12, 3, 14, 1, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ChatId = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 14, 7, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            ReceiverId = 1,
                            SenderId = 2,
                            Text = "Bok,imam naravno,sutra ti dam na faksu.",
                            UpdatedAt = new DateTime(2025, 12, 3, 14, 7, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.PivotTables.CourseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("course_users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 12
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 15
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 12
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 15
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 8,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 9,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 9,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 9,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 10,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 10,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 10,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 10,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 12
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 11,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 11,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 11,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 16
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 13,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 13,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 47,
                            CourseId = 13,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 16
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("roles", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Može samo gledati podatke o kolegijima (nema prava da išta izmijeni)",
                            RoleName = "Student",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Može dodavati studente u kolegije te slati obavijesti i materijale",
                            RoleName = "Professor",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ima ovlasti brisati i dodavati korisnike bilo koje uloge",
                            RoleName = "Admin",
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2000, 4, 4),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zandzartz@gmail.com",
                            FirstName = "John",
                            Gender = "M",
                            LastName = "Doe",
                            Password = "AQAAAAEAACcQAAAAELlVtvsc8M4EiRZ7FmLD4Btf214yEXkXnWlwce2E9hMHsGGeZdZhhZxXvT6/V/dm3w==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2000, 3, 3),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dorianleci@gmail.com",
                            FirstName = "Dorian",
                            Gender = "M",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEL1wJ0JEOjLD2VhH7kB/TXnPNdRahIkEzHiCiPMr/iCP5GVGbunkaanoPiRRa8iN6g==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2004, 3, 28),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "damirleci@gmail.com",
                            FirstName = "Damir",
                            Gender = "M",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAELKCxygVaRPanhMMXMcwMp8YiF1cOt+pc6yaqKKhAMw48frlo2cJgimkPS2wf9YppA==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2005, 11, 28),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vesnaleci@gmail.com",
                            FirstName = "Vesna",
                            Gender = "F",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEOqosTg6DcBkkMfOfHeAwz0F+VwNzFOrLFiMdG0jMr4qqzrb25rOMIakvCwIKkKE8Q==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1990, 10, 12),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zoraleci@gmail.com",
                            FirstName = "Zora",
                            Gender = "F",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEMPvAdlvX5DjAmd++1BhVR/seLcn3LCMbsjayt1c0iU6sdh+q7QGo/TWWBuPzrQfaQ==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1989, 9, 12),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivoivić@gmail.com",
                            FirstName = "Ivo",
                            Gender = "M",
                            LastName = "Ivić",
                            Password = "AQAAAAEAACcQAAAAEEkgqoHclO9AR5eCPQCP6fURv6WlJJNE3bj6ls6SwHSjW8+gYtpsyHuimyB86TSzag==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1988, 9, 12),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petarpetrović@gmail.com",
                            FirstName = "Petar",
                            Gender = "M",
                            LastName = "Petrović",
                            Password = "AQAAAAEAACcQAAAAEJoCDo9HT5s3jZbLoYX/zuZFmRODEZ8ISaTfIWuPrtBddOKRUZ6lutBD5ZN8SbHZ/w==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1995, 1, 1),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "majamajić@gmail.com",
                            FirstName = "Maja",
                            Gender = "F",
                            LastName = "Majić",
                            Password = "AQAAAAEAACcQAAAAEMjWaVzxsRkghmOqPEYSVHOwHAYNXbO0WClhFfLK3yYVKPmzN5pQt01eOswbpN/iTQ==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1997, 2, 2),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vesnavesnić@gmail.com",
                            FirstName = "Vesna",
                            Gender = "F",
                            LastName = "Vesnić",
                            Password = "AQAAAAEAACcQAAAAEBfQsmM1tkjz9bc14N82dVoJhcOXyfvR5sZljOjAtex/+9N4vlf1kpIAiWRuTU+OXQ==",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1997, 3, 8),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sebaleci@gmail.com",
                            FirstName = "Sebastian",
                            Gender = "M",
                            LastName = "Leci",
                            Password = "AQAAAAEAACcQAAAAEFjNqmNq0eTao3nroh4roz5gXYJHQl19ZFtVFo5j19iNxsV22KxoBQ6r5GSFx2h3qg==",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1997, 3, 8),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikolaf@gmail.com",
                            FirstName = "Nikola",
                            Gender = "M",
                            LastName = "Filipović",
                            Password = "AQAAAAEAACcQAAAAEMdYSeuRIbVWW6qPJsTPLylliFsOUt97rFOxMmTwia+RXUALlyJdORFlasPLh9GEJg==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(2004, 3, 8),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tonic@gmail.com",
                            FirstName = "Toni",
                            Gender = "M",
                            LastName = "Crnčić",
                            Password = "AQAAAAEAACcQAAAAEO7xt7VRnkC5bbkrVIK8rH/2Xb4gHzUDX3QCNcWLAzn66uOfwJpsgQREHdR9h++qQA==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(2005, 3, 10),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marijah@gmail.com",
                            FirstName = "Marija",
                            Gender = "F",
                            LastName = "Hanić",
                            Password = "AQAAAAEAACcQAAAAEH8lgFHiNeMBVUPZk85vUxdszpF4raKMSj/RrePHs+8BvLAS8gess82LG3dD1w3/eg==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(2005, 3, 27),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tomislavt@gmail.com",
                            FirstName = "Tomislav",
                            Gender = "M",
                            LastName = "Turjan",
                            Password = "AQAAAAEAACcQAAAAENDR1J3mjWCwNgYLV+cY0JgREqDuEuoh8iXMppuy4RFrXe4rXPRgHKhT08YmTrozXQ==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(2001, 11, 3),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emabolj@gmail.com",
                            FirstName = "Ema",
                            Gender = "F",
                            LastName = "Boljevčan",
                            Password = "AQAAAAEAACcQAAAAEF0hWn2KSQo3ZADOc+BhWOg6lfoAxlrLkvgOGl1kPBqp6U1ngTlyygcQ4wobOj4KlA==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(2003, 10, 17),
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lukajer@gmail.com",
                            FirstName = "Luka",
                            Gender = "M",
                            LastName = "Jerković",
                            Password = "AQAAAAEAACcQAAAAEF4XXYl/MnC1I3n+7Kz1b75TSkh6VH+QNInPopONm4PxofHirRjXf8Pb7xpHKBxGaA==",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Chats.Chat", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "UserA")
                        .WithMany("ChatsAsUserA")
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "UserB")
                        .WithMany("ChatsAsUserB")
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Materials.CourseMaterial", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Notifications.CourseNotification", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Notifications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Messages.PrivateMessage", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Chats.Chat", "Chat")
                        .WithMany("PrivateMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.PivotTables.CourseUser", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_7_Moodle.Domain.Entities.Users.User", "User")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Internship_7_Moodle.Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Chats.Chat", b =>
                {
                    b.Navigation("PrivateMessages");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("Materials");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Internship_7_Moodle.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("ChatsAsUserA");

                    b.Navigation("ChatsAsUserB");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
